[test/migration] fix crash on execution
This assertion is there for unclear reasons.

=====================  unittest_migration.py  =======================
-> creating tables  [====================]
-> inserting default user and default groups.
-> storing the schema in the database  [====================]
-> database for instance data initialized.
F
======================================================================
FAIL: test_db_creation (unittest_migration.BaseCreationTC)
make sure database can be created
----------------------------------------------------------------------
Traceback (most recent call last)
  File "/home/auc/confs/forges/logilab/common/testlib.py", line 661, in _proceed
    testfunc(*args, **kwargs)
  File "/home/auc/confs/forges/cubicweb/test/unittest_migration.py", line 106, in test_db_creation
    handler.build_db_cache()
  File "/home/auc/confs/forges/cubicweb/devtools/__init__.py", line 469, in build_db_cache
    self.init_test_database()
  File "/home/auc/confs/forges/cubicweb/devtools/__init__.py", line 729, in init_test_database
    init_repository(self.config, interactive=False)
  File "/home/auc/confs/forges/cubicweb/server/__init__.py", line 217, in init_repository
    repo = Repository(config, vreg=vreg)
  File "/home/auc/confs/forges/cubicweb/server/repository.py", line 197, in __init__
    self.init_cnxset_pool()
  File "/home/auc/confs/forges/cubicweb/server/repository.py", line 220, in init_cnxset_pool
    config.bootstrap_cubes()
  File "/home/auc/confs/forges/cubicweb/devtools/__init__.py", line 176, in bootstrap_cubes
    super(TestServerConfiguration, self).bootstrap_cubes()
  File "/home/auc/confs/forges/cubicweb/server/serverconfig.py", line 279, in bootstrap_cubes
    self.init_cubes(self.expand_cubes(splitstrip(line)))
  File "/home/auc/confs/forges/cubicweb/cwconfig.py", line 1022, in init_cubes
    super(CubicWebConfiguration, self).init_cubes(cubes)
  File "/home/auc/confs/forges/cubicweb/cwconfig.py", line 798, in init_cubes
    assert self._cubes is None, repr(self._cubes)
AssertionError: ('card', 'file', 'localperms', 'tag')